version: '3.8'
services:
  movies:
    image: gani150/paymovies:latest
    ports:
      - '81:80'
    deploy:
      replicas: 2

  train:
     image: gani150/paytrain:latest
     ports:
       - '84:80'
     deploy:
       replicas: 3
